version: '3.8'

services:
  python-package-volume-init:
    image: debian:bullseye-slim
    user: root
    volumes:
      - type: volume
        source: python-packages
        target: /python-packages
    command: chown -R ${USER_UID}:${USER_GID} /python-packages

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        USERNAME: $USER
        USER_UID: $USER_UID
        USER_GID: $USER_GID
        DOCKER_GID: $DOCKER_GID
    cap_add:
      - SYS_PTRACE
    shm_size: 2GB
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: python-packages
        target: $PWD/.venv
    depends_on:
      python-package-volume-init:
        condition: service_completed_successfully
    command: sleep infinity

volumes:
  python-packages:
